### ISSUE TITLE
net7.0 is not supported

### ISSUE THREAD

**Issue by FreeVB** [UweKeim/ZetaShortPaths#1]
Compilation can be successful in. net4.8. If it is in the. net7.0 environment, the ZlpImpersonator will prompt for a CS0246 error and the Windows ImpersonationContext cannot be found. tempWindowsIdentity.Impersonate(); An error is also prompted.

**Comment by UweKeim** [comment]
The latest version is pure .NET 8, and I removed the impersonator since it has to be done differently in .NET and I only found a way to do it Windows-specific.

If you only need it for Windows, I've attached an example file from another project here.

> [Impersonator.cs](https://github.com/UweKeim/ZetaShortPaths/files/14040759/Impersonator.cs.txt)
